### ISSUE TITLE
🍪☀️ PlutoUI Roadmap ☀️🍪 

### ISSUE THREAD

**Issue by pankgeorg** [JuliaPluto/PlutoUI.jl#208]
# New features enabled by `AbstractPlutoDingetjes.jl` (ConcretePlutoDigetjes.jl)
- [ ] WebCamInput -> returns Image
- [ ] MicrophoneInput -> returns audio (see JuliaMusic?)
- [ ] TableInput -> returns dataframe 
- [ ] Scrubbable matrix -> returns matrix
- [ ] Nice FileInput -> return IO ?? String?? url of file uploaded (somewhere?) ??

# New outputs 
_(use the `<output>` html5 element)_
- [ ] Number output (fix typography, layout)
- [ ] "Dashboard-like" primitive outputs ([statistic](https://ant.design/components/statistic/#header) like)
	- Localization, "type", color, "percent", icon, label, transition using `this` (old clock like)
	- More visual styles for combinations of (text, number)
- [ ] Boolean values (check ✅/❌icon)?
- [ ] Sparklines/data bars? 1em high 
- [ ] DateTime output

# Add HTML 5 features to PlutoUI.*
- [ ] `<label>`
- [ ] `:disabled`
- [ ] `<form>`
- [ ] `<fieldset>`
- [ ] `<output>` 

# Documentation website:
- [ ] Pluto notebook sourcecode should be our documentation!

**Comment by stillyslalom** [comment]
Re: "Pluto notebook sourcecode should be our documentation!"

It's a great idea to have an example/tutorial notebook like [this one](https://juliapluto.github.io/sample-notebook-previews/PlutoUI.jl.html), but good documentation also requires a separate detailed reference for each function. Reference documentation should be somewhat pedantic and repetitive so that the user doesn't have to read the rest of the documentation to figure out the particulars of one function, and that makes for a really bulky notebook. Please consider retaining the Documenter.jl docs (which are... [broken again](https://docs.juliahub.com/PlutoUI/abXFp/0.7.39/)?)
